site_name: JavaFX Documentation
site_url: https://nillnought.github.io/javafx-documentation/
theme:
  name: material
  font:
    text: Roboto
    code: Red Hat Mono
  features:
    - navigation.footer
    - content.code.copy
  #icon:
  # logo: put logo path here

  palette:
  # Dark Mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Dark mode
    primary: amber
    accent: cyan

    #Light Mode
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Light mode
    primary: cyan
    accent: amber

nav:
    - index.md
    - Setting_Up.md
    - Player_Interactions.md
    - Pizzazz.md
    - Troubleshooting.md
    - Glossary.md

#Emojis
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2025 name
